name: Android Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Android project
      run: ./gradlew assembleDebug

    - name: Package APK
      run: cp app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/app-debug.apk
